os: linux
dist: trusty

matrix:
 include:
    - name: "Javascript Contract Tests"
      services:
        - docker
        
      before_script:
        - npm install
        - npm run testrpc &
        
      script:
        - npm run test

      before_install:
        - docker build . -t node
        - docker run --name testrpc --rm -d -it -p 127.0.0.1:8501:8545 node bash
        - docker exec -d -it testrpc /bin/bash ./docker_build/launch_geth.sh

    - name: "Ion-CLI Tests"
      language: go
      go: 1.9.x
      script:
        - cd ./ion-cli
        - go get github.com/ethereum/go-ethereum
        - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
        - dep ensure
        - cp -r "${GOPATH}/src/github.com/ethereum/go-ethereum/crypto/secp256k1/libsecp256k1" "vendor/github.com/ethereum/go-ethereum/crypto/secp256k1/"
        - make build
        - make test
      
      before_install:
        - sudo add-apt-repository ppa:ethereum/ethereum -y
        - sudo apt-get update
        - sudo apt-get install solc -y


notifications:
  slack:
    on_failure: always
    secure: k6j6BWCTMJ6U7JXhy0yBcJpfkOw4eUNnL9xyufiI6Ue5Cf+NvN9FJxNZvoz4BvVSitq/BSlcWGjQoIW5AoWtf15tl4hvQmFN4YYHT79TKjRGEcSBg1+D55aXmjIM3UwHtCOuSJxAkl7dTgWAJ3FU0/aBqy96OsODjhcP8VeuMay+2Z+kT/QQjtO5rduHfLpeJxVfoEdhXR9QjHozV287rE49E6wWV6KzNCDOYy3CFGkQsgBQzlxkmlvhwbjDeNb72UcruSh50ic78/NLru3AXwRFx2yc1fkr2Nv9q6l5r9I1iWek8EZ46OCe/dQ004s7PI7knVx1vssdA3ksLDyRzhNHvWpn1EI1fi4Aqc+ki9vHbccR5c1pw85zwcQiLEoVFpJ+MpfHi9ExmAJmvvrzz2RBMqsL5JuSfInxiSLyX6vSVpufgZYrDKAemWXhR030dQQZ8BVQOCbt2lzCgHZajmDvrOktq6QdTFzEz/JjyorXn+0Rpho+7FHY5sW9KdgvmexI9SAjjz0BgcQzof9QKpyuRZpbboWRxPsfPUQDlx+Wxm541ndunGNQ2mVXqSgKaTQShiKhhu7dOPevw1a+dreJ6n8afL9pfW4SHcs0O+FlHvAnLAbRDvbnxROF89RRDiTVBdC6h7vcAX6lNDFUxF0F1bYTiWE0s4+umB2zlqc=
