os: linux
dist: 1:0.5.1-0ubuntu1~trusty

matrix:
 include:
    - name: "Javascript Contract Tests"
      services:
        - docker
        
      before_script:
        - npm install
        - npm run testrpc &
        
      script:
        - npm run test

      before_install:
        - docker build . -t node
        - docker run --name testrpc --rm -d -it -p 127.0.0.1:8501:8545 node bash
        - docker exec -d -it testrpc /bin/bash ./docker_build/launch_geth.sh

    - name: "Ion-CLI Tests"
      services:
        - docker
        
      before_script:
        - docker exec -it testrpc /bin/bash -c "cd /go/src/github.com/clearmatics/ion/ion-cli; make build; cd /go/src/github.com/ethereum/go-ethereum; git checkout 225171a4bfcc16bd12a1906b1e0d43d0b18c353b; cd /go/src/github.com/clearmatics/ion/ion-cli; make test;"
      
      script:
        - make test
      
      before_install:
        - docker build . -t node
        - docker run --name testrpc --rm -d -it -p 127.0.0.1:8501:8545 node bash


notifications:
  slack:
    on_failure: always
    secure: k6j6BWCTMJ6U7JXhy0yBcJpfkOw4eUNnL9xyufiI6Ue5Cf+NvN9FJxNZvoz4BvVSitq/BSlcWGjQoIW5AoWtf15tl4hvQmFN4YYHT79TKjRGEcSBg1+D55aXmjIM3UwHtCOuSJxAkl7dTgWAJ3FU0/aBqy96OsODjhcP8VeuMay+2Z+kT/QQjtO5rduHfLpeJxVfoEdhXR9QjHozV287rE49E6wWV6KzNCDOYy3CFGkQsgBQzlxkmlvhwbjDeNb72UcruSh50ic78/NLru3AXwRFx2yc1fkr2Nv9q6l5r9I1iWek8EZ46OCe/dQ004s7PI7knVx1vssdA3ksLDyRzhNHvWpn1EI1fi4Aqc+ki9vHbccR5c1pw85zwcQiLEoVFpJ+MpfHi9ExmAJmvvrzz2RBMqsL5JuSfInxiSLyX6vSVpufgZYrDKAemWXhR030dQQZ8BVQOCbt2lzCgHZajmDvrOktq6QdTFzEz/JjyorXn+0Rpho+7FHY5sW9KdgvmexI9SAjjz0BgcQzof9QKpyuRZpbboWRxPsfPUQDlx+Wxm541ndunGNQ2mVXqSgKaTQShiKhhu7dOPevw1a+dreJ6n8afL9pfW4SHcs0O+FlHvAnLAbRDvbnxROF89RRDiTVBdC6h7vcAX6lNDFUxF0F1bYTiWE0s4+umB2zlqc=
