#!/bin/bash

# Launch the boot node
tmux new -s boot -n selsig -d
tmux send-keys -t boot "bootnode -nodekey poa-network/multi-peer/boot.key -verbosity 9 -addr :30310" C-m

# Launch the noodle 1
tmux new -s node1 -n geth_and_console -d
tmux send-keys -t node1 "rm -rf poa-network/multi-peer/node1/geth/chaindata" C-m
tmux send-keys -t node1 "rm -rf poa-network/multi-peer/node2/geth/chaindata" C-m
tmux send-keys -t node1 "geth --datadir poa-network/multi-peer/node1/ init poa-network/multi-peer/genesis.json" C-m
tmux send-keys -t node1 "geth --datadir poa-network/multi-peer/node1/ --syncmode 'full' --port 30311 --rpc --rpcaddr 'localhost' --rpcport 8501 --bootnodes 'enode://dcb1dbf8d710eb7d10e0e2db1e6d3370c4b048efe47c7a85c4b537b60b5c11832ef25f026915b803e928c1d93f01b853131e412c6308c4c6141d1504c78823c8@127.0.0.1:30310' --networkid 1515 --gasprice '0' -unlock '0x2be5ab0e43b6dc2908d5321cf318f35b80d0c10d' --password poa-network/multi-peer/node1/password.txt --mine" C-m
tmux split-window -h -t node1:geth_and_console
tmux send-keys -t node1 "sleep 5s" C-m
tmux send-keys -t node1 "geth attach ipc:poa-network/multi-peer/node1/geth.ipc" C-m

# Launch the noodle 2
tmux new -s node2 -n geth_and_console -d
tmux send-keys -t node2 "geth --datadir poa-network/multi-peer/node2/ init poa-network/multi-peer/genesis.json" C-m
tmux send-keys -t node2 "geth --datadir poa-network/multi-peer/node2/ --syncmode 'full' --port 30312 --rpc --rpcaddr 'localhost' --rpcport 8502 --bootnodes 'enode://dcb1dbf8d710eb7d10e0e2db1e6d3370c4b048efe47c7a85c4b537b60b5c11832ef25f026915b803e928c1d93f01b853131e412c6308c4c6141d1504c78823c8@127.0.0.1:30310' --networkid 1515 --gasprice '0' -unlock '0x8671e5e08d74f338ee1c462340842346d797afd3' --password poa-network/multi-peer/node2/password.txt --mine" C-m
tmux split-window -h -t node2:geth_and_console
tmux send-keys -t node2 "sleep 5s" C-m
tmux send-keys -t node2 "geth attach ipc:poa-network/multi-peer/node2/geth.ipc" C-m

# Launch the noodle 3 - testrpc
tmux new -s node3 -n geth_and_console -d
tmux send-keys -t node3 "npm run testrpc" C-m
tmux split-window -h -t node3:geth_and_console
tmux send-keys -t node3 "sleep 5s" C-m
tmux send-keys -t node3 "geth attach http://127.0.0.1:8545" C-m
tmux ls
