# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ion/proto/chain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ion/proto/chain.proto',
  package='',
  serialized_pb=_b('\n\x15ion/proto/chain.proto\"#\n\x05\x42lock\x12\x0c\n\x04prev\x18\x01 \x02(\x0c\x12\x0c\n\x04root\x18\x02 \x02(\x0c\"9\n\x0bPaymentLink\x12\t\n\x01t\x18\x01 \x02(\x0c\x12\t\n\x01\x63\x18\x02 \x02(\x0c\x12\t\n\x01v\x18\x03 \x02(\x04\x12\t\n\x01r\x18\x04 \x03(\x0c\"K\n\x07Payment\x12\t\n\x01\x66\x18\x01 \x02(\x0c\x12\t\n\x01t\x18\x02 \x02(\x0c\x12\t\n\x01\x63\x18\x03 \x02(\x0c\x12\t\n\x01v\x18\x04 \x02(\x04\x12\t\n\x01r\x18\x05 \x03(\x0c\x12\t\n\x01\x64\x18\x06 \x03(\x0c\"1\n\x0e\x45\x63\x64saSignature\x12\t\n\x01v\x18\x01 \x02(\x0c\x12\t\n\x01r\x18\x02 \x02(\x0c\x12\t\n\x01s\x18\x03 \x02(\x0c\"K\n\rSignedPayment\x12\x13\n\x01p\x18\x01 \x02(\x0b\x32\x08.Payment\x12 \n\x05\x65\x63\x64sa\x18\x02 \x01(\x0b\x32\x0f.EcdsaSignatureH\x00\x42\x03\n\x01s\">\n\rBlockPayments\x12\x11\n\x01\x62\x18\x01 \x02(\x0b\x32\x06.Block\x12\x1a\n\x02sp\x18\x02 \x03(\x0b\x32\x0e.SignedPayment')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prev', full_name='Block.prev', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='root', full_name='Block.root', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=60,
)


_PAYMENTLINK = _descriptor.Descriptor(
  name='PaymentLink',
  full_name='PaymentLink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='t', full_name='PaymentLink.t', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c', full_name='PaymentLink.c', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v', full_name='PaymentLink.v', index=2,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r', full_name='PaymentLink.r', index=3,
      number=4, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=119,
)


_PAYMENT = _descriptor.Descriptor(
  name='Payment',
  full_name='Payment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='f', full_name='Payment.f', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='t', full_name='Payment.t', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='c', full_name='Payment.c', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='v', full_name='Payment.v', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r', full_name='Payment.r', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='d', full_name='Payment.d', index=5,
      number=6, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=196,
)


_ECDSASIGNATURE = _descriptor.Descriptor(
  name='EcdsaSignature',
  full_name='EcdsaSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='v', full_name='EcdsaSignature.v', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='r', full_name='EcdsaSignature.r', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='s', full_name='EcdsaSignature.s', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=247,
)


_SIGNEDPAYMENT = _descriptor.Descriptor(
  name='SignedPayment',
  full_name='SignedPayment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='SignedPayment.p', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecdsa', full_name='SignedPayment.ecdsa', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='s', full_name='SignedPayment.s',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=249,
  serialized_end=324,
)


_BLOCKPAYMENTS = _descriptor.Descriptor(
  name='BlockPayments',
  full_name='BlockPayments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='b', full_name='BlockPayments.b', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sp', full_name='BlockPayments.sp', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=388,
)

_SIGNEDPAYMENT.fields_by_name['p'].message_type = _PAYMENT
_SIGNEDPAYMENT.fields_by_name['ecdsa'].message_type = _ECDSASIGNATURE
_SIGNEDPAYMENT.oneofs_by_name['s'].fields.append(
  _SIGNEDPAYMENT.fields_by_name['ecdsa'])
_SIGNEDPAYMENT.fields_by_name['ecdsa'].containing_oneof = _SIGNEDPAYMENT.oneofs_by_name['s']
_BLOCKPAYMENTS.fields_by_name['b'].message_type = _BLOCK
_BLOCKPAYMENTS.fields_by_name['sp'].message_type = _SIGNEDPAYMENT
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['PaymentLink'] = _PAYMENTLINK
DESCRIPTOR.message_types_by_name['Payment'] = _PAYMENT
DESCRIPTOR.message_types_by_name['EcdsaSignature'] = _ECDSASIGNATURE
DESCRIPTOR.message_types_by_name['SignedPayment'] = _SIGNEDPAYMENT
DESCRIPTOR.message_types_by_name['BlockPayments'] = _BLOCKPAYMENTS

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(
  DESCRIPTOR = _BLOCK,
  __module__ = 'ion.proto.chain_pb2'
  # @@protoc_insertion_point(class_scope:Block)
  ))
_sym_db.RegisterMessage(Block)

PaymentLink = _reflection.GeneratedProtocolMessageType('PaymentLink', (_message.Message,), dict(
  DESCRIPTOR = _PAYMENTLINK,
  __module__ = 'ion.proto.chain_pb2'
  # @@protoc_insertion_point(class_scope:PaymentLink)
  ))
_sym_db.RegisterMessage(PaymentLink)

Payment = _reflection.GeneratedProtocolMessageType('Payment', (_message.Message,), dict(
  DESCRIPTOR = _PAYMENT,
  __module__ = 'ion.proto.chain_pb2'
  # @@protoc_insertion_point(class_scope:Payment)
  ))
_sym_db.RegisterMessage(Payment)

EcdsaSignature = _reflection.GeneratedProtocolMessageType('EcdsaSignature', (_message.Message,), dict(
  DESCRIPTOR = _ECDSASIGNATURE,
  __module__ = 'ion.proto.chain_pb2'
  # @@protoc_insertion_point(class_scope:EcdsaSignature)
  ))
_sym_db.RegisterMessage(EcdsaSignature)

SignedPayment = _reflection.GeneratedProtocolMessageType('SignedPayment', (_message.Message,), dict(
  DESCRIPTOR = _SIGNEDPAYMENT,
  __module__ = 'ion.proto.chain_pb2'
  # @@protoc_insertion_point(class_scope:SignedPayment)
  ))
_sym_db.RegisterMessage(SignedPayment)

BlockPayments = _reflection.GeneratedProtocolMessageType('BlockPayments', (_message.Message,), dict(
  DESCRIPTOR = _BLOCKPAYMENTS,
  __module__ = 'ion.proto.chain_pb2'
  # @@protoc_insertion_point(class_scope:BlockPayments)
  ))
_sym_db.RegisterMessage(BlockPayments)


# @@protoc_insertion_point(module_scope)
